# The purpose of this configuration is to run a machine learning training job using the specified image.
# Before deploying this configuration, you need to replace the "image" field below with the URL of the Docker image you want to use for your machine learning training job.
# The image is a Docker image that contains the training code and the required libraries.
# The node selector and tolerations are required because the Trainium nodes are tainted to prevent other workloads from running on them.

---
apiVersion: v1
kind: Pod
metadata:
  name: trn1-mlp
spec:
  restartPolicy: Never
  # schedulerName: default-scheduler
  nodeSelector:
    node.kubernetes.io/instance-type: trn1.32xlarge
    provisioner: trainium-trn1
    NodeGroupType: trainium-karpenter
  tolerations:
    - key: "trn1-karpenter"
      value: "true"
      effect: "NoSchedule"
  containers:
    - name: trn1-mlp
      command: ['torchrun']
      args:
        - '--nnodes=1'
        - '--nproc_per_node=32'
        - 'train_torchrun.py'
      image: <ACCOUNTID>.dkr.ecr.<REGION>.amazonaws.com/eks_mlperf_training:mlp
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          aws.amazon.com/neuron: 16
